-- Artist table
CREATE TABLE artist (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        name VARCHAR(100) NOT NULL,
                        description CLOB,
                        PRIMARY KEY (id),
                        CONSTRAINT uk_artist_name UNIQUE (name)
);

-- Author table
CREATE TABLE author (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        name VARCHAR(100) NOT NULL,
                        PRIMARY KEY (id),
                        CONSTRAINT uk_author_name UNIQUE (name)
);

-- LP table
CREATE TABLE lp (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    name VARCHAR(100) NOT NULL,
                    description CLOB,
                    artist_id BIGINT NOT NULL,
                    PRIMARY KEY (id),
                    CONSTRAINT fk_lp_artist FOREIGN KEY (artist_id) REFERENCES artist(id)
);

-- Song table
CREATE TABLE song (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      title VARCHAR(200) NOT NULL,
                      lp_id BIGINT NOT NULL,
                      PRIMARY KEY (id),
                      CONSTRAINT fk_song_lp FOREIGN KEY (lp_id) REFERENCES lp(id)
);

-- Song-Author join table (N:N)
CREATE TABLE song_author (
                             song_id BIGINT NOT NULL,
                             author_id BIGINT NOT NULL,
                             PRIMARY KEY (song_id, author_id),
                             CONSTRAINT fk_song_author_song FOREIGN KEY (song_id) REFERENCES song(id),
                             CONSTRAINT fk_song_author_author FOREIGN KEY (author_id) REFERENCES author(id)
);
